version: '3.8'

services:
  app:
    image: vikky225/customer-contacts-app:latest
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: docker
    depends_on:
      - db

  db:
    image: postgres:13
    environment:
      POSTGRES_DB: customer_contacts
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5433:5432"