apiVersion: apps/v1
kind: Deployment
metadata:
  name: customer-contacts-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: customer-contacts-app
  template:
    metadata:
      labels:
        app: customer-contacts-app
    spec:
      containers:
        - name: customer-contacts-app
          image: vikky225/customer-contacts-app:latest
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: docker
---
apiVersion: v1
kind: Service
metadata:
  name: customer-contacts-app
spec:
  type: LoadBalancer
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: customer-contacts-app