@customerId = 2
@phoneNumber = +1234567890

# GET all phone numbers
GET http://localhost:8080/api/phone-numbers
Content-Type: application/json

<> 2025-01-21T231822.200.json

###

# GET phone numbers for a specific customer
GET http://localhost:8080/api/customers/{{customerId}}/phone-numbers
Content-Type: application/json



# POST activate a phone number for a customer
# POST http://localhost:8080/api/customers/{customerId}/phone-numbers?phoneNumber={phoneNumber}
# Content-Type: application/json

