@customerId = 2
@phoneNumber = +1234567890

# GET all phone numbers
GET http://localhost:8080/phone-numbers
Content-Type: application/json

<> 2025-01-21T231822.200.json

###

# GET phone numbers for a specific customer
GET http://localhost:8080/phone-numbers?customerId={{customerId}}
Content-Type: application/json

<> 2025-01-22T050052.200.json
<> 2025-01-22T050031.200.json
<> 2025-01-22T050004.200.json
<> 2025-01-21T231836.200.json

###

# POST to activate a phone number for a customer
POST http://localhost:8080/phone-numbers/{{customerId}}?phoneNumber={{phoneNumber}}
Content-Type: application/json


###
GET http://localhost:8080/phone-numbers

###
POST http://localhost:8080/phone-numbers/{{customerId}}?
    phoneNumber={{$placeholder}}