name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 21
        uses: actions/setup-java@v2
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Install Docker Compose
        run: |
          sudo curl -L "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose    

      - name: Build with Maven
        run: mvn clean package

      - name: Build Docker image
        run: docker build -t vikky225/customer-contacts-app:latest .

      - name: Log in to DockerHub
        run: echo "${{ secrets.DOCKERHUB_PASSWORD }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

      - name: Push Docker image
        run: docker push vikky225/customer-contacts-app:latest

      - name: Run Docker Compose
        run: docker-compose up -d

  deploy:
    runs-on: aws-ec2
    needs: build

    steps:
      - name: Install Docker
        run: |
          sudo apt-get update
          sudo apt-get install -y docker.io

      - name: Pull Image from Docker
        run: sudo docker pull vikky225/customer-contacts-app:latest

      - name: Removing Existing Container
        run: sudo docker rm -f customer-container || true
      - name: Run docker container
        run: sudo docker run -d -p 8080:8080 --name customer-container vikky225/customer-contacts-app:latest

