name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 21
        uses: actions/setup-java@v2
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Build with Maven
        run: mvn clean package

      - name: Build Docker image
        run: docker build -t vikky225/customer-contacts-app:latest .

      - name: Log in to DockerHub
        run: echo "${{ secrets.DOCKERHUB_PASSWORD }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

      - name: Push Docker image
        run: docker push vikky225/customer-contacts-app:latest

      - name: Run Docker Compose
        run: docker-compose up --build

  deploy:
    runs-on: aws-ec2
    needs: build

    steps:
      - name: Pull Image from Docker
        run: docker pull vikky225/customer-contacts-app:latest

      - name: Removing Existing Container
        run: docker rm -f customer-container || true
      - name: Run docker container
        run: docker run -d -p 8080:8080 --name customer-container vikky225/customer-contacts-app:latest

